// flow-typed signature: d179918f60a47033c9024c6affde6dca
// flow-typed version: <<STUB>>/flow-babel-webpack-plugin_v1.0.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow-babel-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow-babel-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'flow-babel-webpack-plugin/index' {
  declare module.exports: $Exports<'flow-babel-webpack-plugin'>;
}
declare module 'flow-babel-webpack-plugin/index.js' {
  declare module.exports: $Exports<'flow-babel-webpack-plugin'>;
}
